#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Simple script to translate Russian strings to English in pacifica_bot.py"""

import re

# Read the original file
with open('pacifica_bot.py', 'r', encoding='utf-8') as f:
    content = f.read()

# Simple translation function for common patterns
def translate_text(text):
    """Translate Russian text to English"""
    # This is a simplified approach - in reality you'd want a proper translation
    # For now, we'll do key replacements
    
    # Common patterns
    replacements = {
        'Инициализация': 'Initialization',
        'клиентов': 'clients',
        'Закрытие': 'Closing',
        'соединений': 'connections',
        'Получение': 'Getting',
        'информации': 'information',
        'об': 'about',
        'аккаунте': 'account',
        'доступного': 'available',
        'баланса': 'balance',
        'списка': 'list',
        'рынков': 'markets',
        'текущих': 'current',
        'цен': 'prices',
        'таймаутом': 'with timeout',
        'повторными': 'with retry',
        'попытками': 'attempts',
        'Ошибка': 'Error',
        'Не удалось': 'Failed to',
        'Попытка': 'Attempt',
        'через': 'via',
        'не удалась': 'failed',
        'настроен': 'configured',
        'подписью': 'with signature',
        'авторизованных': 'authorized',
        'запросов': 'requests',
        'инициализированы': 'initialized',
        'не имеет': 'does not have',
        'к': 'to',
        'приватным': 'private',
        'эндпоинтам': 'endpoints',
        'могут': 'may',
        'не работать': 'not work',
    }
    
    # Apply replacements
    for ru, en in replacements.items():
        text = text.replace(ru, en)
    
    return text

# For now, let's just do a simple find-replace for the most common patterns
# We'll need to do this more systematically

# Replace docstrings
content = re.sub(r'"""Инициализация клиентов"""', '"""Initializing clients"""', content)
content = re.sub(r'"""Закрытие соединений"""', '"""Closing connections"""', content)
content = re.sub(r'"""Получение информации об аккаунте"""', '"""Getting account information"""', content)
content = re.sub(r'"""Получение доступного баланса"""', '"""Getting available balance"""', content)
content = re.sub(r'"""Получение списка рынков"""', '"""Getting list of markets"""', content)
content = re.sub(r'"""Получение текущих цен с таймаутом и повторными попытками"""', '"""Getting current prices with timeout and retries"""', content)
content = re.sub(r'"""Получение текущей цены для символа"""', '"""Getting current price for symbol"""', content)
content = re.sub(r'"""Получение funding rate для символа"""', '"""Getting funding rate for symbol"""', content)
content = re.sub(r'"""Получение tick size для символа"""', '"""Getting tick size for symbol"""', content)
content = re.sub(r'"""Получение lot size \(минимальный размер ордера\) для символа"""', '"""Getting lot size (minimum order size) for symbol"""', content)
content = re.sub(r'"""Округление количества до кратного lot size"""', '"""Rounding amount to lot size multiple"""', content)
content = re.sub(r'"""Округление цены до кратного tick size"""', '"""Rounding price to tick size multiple"""', content)
content = re.sub(r'"""Получение максимального плеча для рынка"""', '"""Getting maximum leverage for market"""', content)
content = re.sub(r'"""Установка плеча для рынка\s+Для открытых позиций можно только увеличивать плечо"""', '"""Setting leverage for market\n        \n        For open positions, leverage can only be increased"""', content)
content = re.sub(r'"""Получение открытых позиций с повторными попытками"""', '"""Getting open positions with retries"""', content)
content = re.sub(r'"""Размещение ордера\s+Args:.*?reduce_only: Только для закрытия позиции\s+"""', '"""Placing order\n        \n        Args:\n            symbol: Trading symbol (e.g. "BTC")\n            side: Side.BID (buy) or Side.ASK (sell)\n            size_usd: Position size in USD\n            price: Price for limit order (if None - market order)\n            reduce_only: Only for closing position\n        """', content, flags=re.DOTALL)
content = re.sub(r'"""Отмена ордера"""', '"""Canceling order"""', content)
content = re.sub(r'"""Получение открытых ордеров"""', '"""Getting open orders"""', content)
content = re.sub(r'"""Отмена всех ордеров"""', '"""Canceling all orders"""', content)
content = re.sub(r'"""Закрытие всех открытых позиций\s+Returns:.*?False если ошибка\s+"""', '"""Closing all open positions\n        \n        Returns:\n            True if all positions closed or there were none, False if error\n        """', content, flags=re.DOTALL)
content = re.sub(r'"""Очистка перед новой сделкой:.*?Закрывает все открытые позиции\s+"""', '"""Cleaning up before new trade:\n        - Cancels all open orders\n        - Closes all open positions\n        """', content, flags=re.DOTALL)
content = re.sub(r'"""Закрытие позиции"""', '"""Closing position"""', content)
content = re.sub(r'"""Установка Take Profit и Stop Loss для позиции через API"""', '"""Setting Take Profit and Stop Loss for position via API"""', content)
content = re.sub(r'"""Выбор лучшего рынка на основе funding rate"""', '"""Selecting best market based on funding rate"""', content)
content = re.sub(r'"""Определение направления на основе funding rate"""', '"""Determining direction based on funding rate"""', content)
content = re.sub(r'"""Один цикл торговли\s+Returns:.*?False иначе\s+"""', '"""One trading cycle\n        \n        Returns:\n            True if target volume reached, False otherwise\n        """', content, flags=re.DOTALL)
content = re.sub(r'"""Ожидание исполнения ордера и получение реальной цены\s+Строго по документации Pacifica:.*?3\. Get order history by ID - история ордера\s+"""', '"""Waiting for order execution and getting real price\n        \n        Strictly according to Pacifica documentation:\n        https://docs.pacifica.fi/api-documentation/api/rest-api/orders\n        \n        Checks:\n        1. Get open orders - open orders\n        2. Get account positions - open positions\n        3. Get order history by ID - order history\n        """', content, flags=re.DOTALL)
content = re.sub(r'"""Удержание позиции с мониторингом"""', '"""Holding position with monitoring"""', content)
content = re.sub(r'"""Расчет PnL"""', '"""Calculating PnL"""', content)
content = re.sub(r'"""Запуск бота"""', '"""Starting bot"""', content)
content = re.sub(r'"""Главная функция"""', '"""Main function"""', content)

# Replace logger messages - this is a simplified version
# In reality, you'd want to translate each message individually
logger_patterns = [
    (r'Инициализация Pacifica клиентов\.\.\.', 'Initializing Pacifica clients...'),
    (r'✓ Info настроен с подписью для авторизованных GET запросов', '✓ Info configured with signature for authorized GET requests'),
    (r'⚠ Exchange не имеет keypair - GET запросы к приватным эндпоинтам могут не работать', '⚠ Exchange does not have keypair - GET requests to private endpoints may not work'),
    (r'✓ Клиенты инициализированы', '✓ Clients initialized'),
    (r'Попытка через Info не удалась:', 'Attempt via Info failed:'),
    (r'Ошибка HTTP (\d+):', r'HTTP error \1:'),
    (r'Ошибка получения аккаунта:', 'Error getting account:'),
    (r'Ошибка получения рынков:', 'Error getting markets:'),
    (r'Запрос цен через API \(попытка (\d+)/(\d+)\)\.\.\.', r'Requesting prices via API (attempt \1/\2)...'),
    (r'✓ Получено цен: (\d+)', r'✓ Received prices: \1'),
    (r'Пустой ответ от API \(попытка (\d+)/(\d+)\)', r'Empty response from API (attempt \1/\2)'),
    (r'Таймаут получения цен \(попытка (\d+)/(\d+)\)', r'Timeout getting prices (attempt \1/\2)'),
    (r'Ошибка получения цен \(попытка (\d+)/(\d+)\):', r'Error getting prices (attempt \1/\2):'),
    (r'CloudFront блокирует, ждём (\d+)с\.\.\.', r'CloudFront is blocking, waiting \1s...'),
    (r'Не удалось получить цены после всех попыток', 'Failed to get prices after all attempts'),
    (r'Цена ([A-Z]+): \$([\d.]+)', r'Price \1: $\2'),
    (r'Цена ([A-Z]+) не найдена в prices, пробуем через markets\.\.\.', r'Price \1 not found in prices, trying via markets...'),
    (r'Цена ([A-Z]+) из markets: \$([\d.]+)', r'Price \1 from markets: $\2'),
    (r'Ошибка получения цены через markets:', 'Error getting price via markets:'),
    (r'Не удалось получить цену для ([A-Z]+)', r'Failed to get price for \1'),
    (r'Максимальное плечо для ([A-Z]+): (\d+)x', r'Maximum leverage for \1: \2x'),
    (r'Ошибка получения максимального плеча для ([A-Z]+):', r'Error getting maximum leverage for \1:'),
    (r'Найдена открытая позиция ([A-Z]+) с плечом (\d+)x', r'Found open position \1 with leverage \2x'),
    (r'⚠ Для открытой позиции ([A-Z]+) можно только УВЕЛИЧИВАТЬ плечо\. Текущее: (\d+)x, запрошенное: (\d+)x\. Используем текущее (\d+)x', r'⚠ For open position \1 leverage can only be INCREASED. Current: \2x, requested: \3x. Using current \4x'),
    (r'Плечо ([A-Z]+) уже установлено на (\d+)x', r'Leverage \1 already set to \2x'),
    (r'Плечо (\d+)x превышает максимальное для ([A-Z]+) \((\d+)x\)\. Используем (\d+)x', r'Leverage \1x exceeds maximum for \2 (\3x). Using \4x'),
    (r'Плечо (\d+)x слишком мало для ([A-Z]+)\. Используем минимальное 1x', r'Leverage \1x too low for \2. Using minimum 1x'),
    (r'Не удалось получить максимальное плечо для ([A-Z]+), используем запрошенное (\d+)x', r'Failed to get maximum leverage for \1, using requested \2x'),
    (r'✓ Плечо (\d+)x установлено для ([A-Z]+)', r'✓ Leverage \1x set for \2'),
    (r'✗ Нельзя уменьшить плечо для открытой позиции ([A-Z]+)\. Текущее: (\d+)x, запрошенное: (\d+)x', r'✗ Cannot decrease leverage for open position \1. Current: \2x, requested: \3x'),
    (r'Плечо (\d+)x недопустимо для ([A-Z]+) с открытой позицией\. Текущее: (\d+)x\. Пробуем увеличить\.\.\.', r'Leverage \1x invalid for \2 with open position. Current: \3x. Trying to increase...'),
    (r'Пробуем установить плечо (\d+)x для ([A-Z]+)\.\.\.', r'Trying to set leverage \1x for \2...'),
    (r'✓ Плечо (\d+)x установлено для ([A-Z]+) \(вместо запрошенного (\d+)x\)', r'✓ Leverage \1x set for \2 (instead of requested \3x)'),
    (r'✗ Не удалось установить допустимое плечо для ([A-Z]+) с открытой позицией', r'✗ Failed to set valid leverage for \1 with open position'),
    (r'Плечо (\d+)x недопустимо для ([A-Z]+) \(ошибка: ([^)]+)\), пробуем уменьшить\.\.\.', r'Leverage \1x invalid for \2 (error: \3), trying to decrease...'),
    (r'Последняя ошибка: (.+)', r'Last error: \1'),
    (r'Ошибка установки плеча для ([A-Z]+): \[(\d+)\] code=([^ ]+) message=\'([^\']+)\'', r'Error setting leverage for \1: [\2] code=\3 message=\'\4\''),
    (r'Плечо (\d+)x недопустимо для ([A-Z]+), пробуем уменьшить\.\.\.', r'Leverage \1x invalid for \2, trying to decrease...'),
    (r'Обновляем текущее плечо для этого рынка', 'Updating current leverage for this market'),
    (r'✗ Не удалось установить допустимое плечо для ([A-Z]+): (.+)', r'✗ Failed to set valid leverage for \1: \2'),
    (r'Ошибка установки плеча для ([A-Z]+): (.+)', r'Error setting leverage for \1: \2'),
    (r'Traceback:', 'Traceback:'),
    (r'✓ Получено позиций: (\d+)', r'✓ Received positions: \1'),
    (r'Позиция: ([A-Z]+), amount=([^,]+), entry_price=([^)]+)', r'Position: \1, amount=\2, entry_price=\3'),
    (r'CloudFront блокирует \(попытка (\d+)/(\d+)\), ждём ([\d.]+)с\.\.\.', r'CloudFront is blocking (attempt \1/\2), waiting \3s...'),
    (r'CloudFront блокирует после (\d+) попыток, возвращаем пустой список', r'CloudFront is blocking after \1 attempts, returning empty list'),
    (r'Ошибка получения позиций:', 'Error getting positions:'),
    (r'Размер округлён до lot size ([\d.]+): ([\d.]+) ([A-Z]+)', r'Size rounded to lot size \1: \2 \3'),
    (r'Размер ордера слишком мал: ([\d.]+)', r'Order size too small: \1'),
    (r'✓ Ордер размещен: (.+) ([\d.]+) ([A-Z]+) \(\$([\d.]+)\)', r'✓ Order placed: \1 \2 \3 ($\4)'),
    (r'Ошибка размещения ордера:', 'Error placing order:'),
    (r'✓ Ордер #(\d+) отменён', r'✓ Order #\1 cancelled'),
    (r'Ошибка отмены ордера #(\d+):', r'Error canceling order #\1:'),
    (r'Ошибка получения открытых ордеров:', 'Error getting open orders:'),
    (r'Отмена всех ордеров для ([A-Z]+)\.\.\.', r'Canceling all orders for \1...'),
    (r'Отмена всех ордеров для всех символов\.\.\.', 'Canceling all orders for all symbols...'),
    (r'✓ Отменено ордеров: (\d+)', r'✓ Cancelled orders: \1'),
    (r'Не удалось получить информацию об отменённых ордерах', 'Failed to get information about cancelled orders'),
    (r'Ошибка отмены всех ордеров:', 'Error canceling all orders:'),
    (r'Нет открытых позиций для закрытия', 'No open positions to close'),
    (r'Закрытие позиции ([A-Z]+)\.\.\.', r'Closing position \1...'),
    (r'✓ Закрыто позиций: (\d+)', r'✓ Closed positions: \1'),
    (r'Ошибка закрытия всех позиций:', 'Error closing all positions:'),
    (r'🧹 Очистка перед новой сделкой\.\.\.', '🧹 Cleaning up before new trade...'),
    (r'✓ Очистка завершена', '✓ Cleanup completed'),
    (r'Не удалось получить цену для закрытия позиции ([A-Z]+)', r'Failed to get price for closing position \1'),
    (r'Закрытие позиции ([A-Z]+): позиция (.+), закрываем через (.+), размер: ([\d.]+) \(([\d.]+) USD\)', r'Closing position \1: position \2, closing via \3, size: \4 (\5 USD)'),
    (r'Позиция ([A-Z]+) закрыта, проверяем открытые ордера\.\.\.', r'Position \1 closed, checking open orders...'),
    (r'Найдено (\d+) открытых ордеров для ([A-Z]+), отменяем\.\.\.', r'Found \1 open orders for \2, cancelling...'),
    (r'✓ Ордер #(\d+) отменён', r'✓ Order #\1 cancelled'),
    (r'Не удалось отменить ордер #(\d+):', r'Failed to cancel order #\1:'),
    (r'Нет открытых ордеров для ([A-Z]+)', r'No open orders for \1'),
    (r'Позиции ([A-Z]+) нет, но найдено (\d+) открытых ордеров, отменяем\.\.\.', r'Position \1 not found, but found \2 open orders, cancelling...'),
    (r'Сторона позиции не совпадает: ожидали (.+), получили (.+)', r'Position side does not match: expected \1, got \2'),
    (r'Позиция ([A-Z]+) не найдена, не можем установить TP/SL', r'Position \1 not found, cannot set TP/SL'),
    (r'Не удалось получить tick_size для ([A-Z]+), используем округление до 2 знаков', r'Failed to get tick_size for \1, using rounding to 2 decimal places'),
    (r'Расчёт TP/SL для ([A-Z]+) \((.+)\): Entry=([\d.]+), TP=([\d.]+), SL=([\d.]+)', r'Calculating TP/SL for \1 (\2): Entry=\3, TP=\4, SL=\5'),
    (r'Отправка запроса TP/SL: symbol=([A-Z]+), позиция=(.+), стоп-ордера=(.+)', r'Sending TP/SL request: symbol=\1, position=\2, stop orders=\3'),
    (r'✓ TP/SL установлены для ([A-Z]+) \((.+)\): TP @ ([\d.]+) \(\+([\d.]+)%\), SL @ ([\d.]+) \(-([\d.]+)%\)', r'✓ TP/SL set for \1 (\2): TP @ \3 (+\4%), SL @ \5 (-\6%)'),
    (r'⚠ Не удалось установить TP/SL для ([A-Z]+): (.+)', r'⚠ Failed to set TP/SL for \1: \2'),
    (r'Пустой ответ от API при установке TP/SL для ([A-Z]+)', r'Empty response from API when setting TP/SL for \1'),
    (r'API ошибка при установке TP/SL для ([A-Z]+): \[(\d+)\] code=([^ ]+) message=\'([^\']+)\' data=(.+)', r'API error when setting TP/SL for \1: [\2] code=\3 message=\'\4\' data=\5'),
    (r'Server ошибка при установке TP/SL для ([A-Z]+): (.+)', r'Server error when setting TP/SL for \1: \2'),
    (r'Ошибка установки TP/SL для ([A-Z]+): (.+)', r'Error setting TP/SL for \1: \2'),
    (r'Ошибка анализа ([A-Z]+):', r'Error analyzing \1:'),
    (r'Не удалось получить funding rate для ([A-Z]+)', r'Failed to get funding rate for \1'),
    (r'Funding rate для ([A-Z]+): ([\d.]+) \(([\d.]+)%\)', r'Funding rate for \1: \2 (\3%)'),
    (r'Funding rate положительный, открываем SHORT \(получаем funding\)', 'Funding rate positive, opening SHORT (receiving funding)'),
    (r'Funding rate отрицательный, открываем LONG \(получаем funding\)', 'Funding rate negative, opening LONG (receiving funding)'),
    (r'Нет доступных рынков', 'No available markets'),
    (r'Выбран рынок: ([A-Z]+)', r'Selected market: \1'),
    (r'Не удалось определить направление для ([A-Z]+)', r'Failed to determine direction for \1'),
    (r'Недостаточно средств или баланс не получен', 'Insufficient funds or balance not received'),
    (r'Не удалось получить цену для ([A-Z]+)', r'Failed to get price for \1'),
    (r'Размер позиции: ([\d.]+)% от баланса \(\$([\d.]+) без плеча → \$([\d.]+) с плечом (\d+)x\)', r'Position size: \1% of balance ($\2 without leverage → $\3 with leverage \4x)'),
    (r'Размер позиции уменьшен до ([\d.]+)% \(\$([\d.]+) без плеча, \$([\d.]+) с плечом (\d+)x\)', r'Position size decreased to \1% ($\2 without leverage, $\3 with leverage \4x)'),
    (r'Лимитная цена: ([\d.]+) \(текущая: ([\d.]+), отступ: ([\d.]+)%\)', r'Limit price: \1 (current: \2, offset: \3%)'),
    (r'Не удалось открыть позицию', 'Failed to open position'),
    (r'Ожидание исполнения ордера\.\.\.', 'Waiting for order execution...'),
    (r'❌ Ордер не был исполнен - позиция НЕ открыта', '❌ Order was not executed - position NOT opened'),
    (r'Бот пропустит эту сделку и перейдёт к следующей', 'Bot will skip this trade and move to next'),
    (r'✓ Позиция открыта @ ([\d.]+)', r'✓ Position opened @ \1'),
    (r'Установка Take Profit и Stop Loss через API\.\.\.', 'Setting Take Profit and Stop Loss via API...'),
    (r'⚠ Не удалось установить TP/SL через API, бот будет мониторить вручную', '⚠ Failed to set TP/SL via API, bot will monitor manually'),
    (r'Удержание позиции (\d+) минут \(([\d.]+) секунд\)\.\.\.', r'Holding position \1 minutes (\2 seconds)...'),
    (r'Закрытие позиции ([A-Z]+)\.\.\.', r'Closing position \1...'),
    (r'Не удалось получить цену закрытия', 'Failed to get closing price'),
    (r'Не удалось закрыть позицию', 'Failed to close position'),
    (r'✓ Сделка #(\d+) закрыта \| Exit: ([\d.]+) \| PnL: \$([\d.]+)', r'✓ Trade #\1 closed | Exit: \2 | PnL: $\3'),
    (r'Объём сделки: \$([\d.]+) \| Общий объём: \$([\d.]+) \| Общий PnL: \$([\d.]+)', r'Trade volume: $\1 | Total volume: $\2 | Total PnL: $\3'),
    (r'=== Ожидание исполнения ордера #(\d+) ===', r'=== Waiting for order execution #\1 ==='),
    (r'Рынок: ([A-Z]+), Сторона: (.+), Лимитная цена: (.+)', r'Market: \1, Side: \2, Limit price: \3'),
    (r'Market ордер - проверяем исполнение\.\.\.', 'Market order - checking execution...'),
    (r'✓ Market ордер исполнен @ ([\d.]+)', r'✓ Market order executed @ \1'),
    (r'✓ Market ордер исполнен! Позиция: ([\d.]+) ([A-Z]+) @ ([\d.]+)', r'✓ Market order executed! Position: \1 \2 @ \3'),
    (r'Максимум ожидания: (\d+)с, перестановка через: (\d+)с', r'Maximum wait: \1s, repositioning via: \2s'),
    (r'Интервал проверки: (\d+)с', r'Check interval: \1s'),
    (r'\[(\d+)с\] Проверка позиций для ([A-Z]+)\.\.\.', r'[\1s] Checking positions for \2...'),
    (r'Получено позиций: (\d+)', r'Received positions: \1'),
    (r'Позиция: symbol=([A-Z]+), amount=(.+)', r'Position: symbol=\1, amount=\2'),
    (r'✓ Найдена позиция по ([A-Z]+): amount=(.+)', r'✓ Found position for \1: amount=\2'),
    (r'✓✓✓ ОРДЕР #(\d+) ИСПОЛНЕН! ✓✓✓', r'✓✓✓ ORDER #\1 EXECUTED! ✓✓✓'),
    (r'⚠ Позиция найдена, но amount слишком мал: (.+)', r'⚠ Position found, but amount too small: \1'),
    (r'Открытых ордеров: (\d+)', r'Open orders: \1'),
    (r'Ордер #(\d+) найден в открытых ордерах', r'Order #\1 found in open orders'),
    (r'Заполнение: filled=([\d.]+), initial=([\d.]+), cancelled=([\d.]+)', r'Filling: filled=\1, initial=\2, cancelled=\3'),
    (r'Осталось: ([\d.]+) \(([\d.]+)%\)', r'Remaining: \1 (\2%)'),
    (r'✓ Ордер #(\d+) почти исполнен! @ ([\d.]+)', r'✓ Order #\1 almost executed! @ \2'),
    (r'✓ Позиция подтверждена: ([\d.]+) ([A-Z]+) @ ([\d.]+)', r'✓ Position confirmed: \1 \2 @ \3'),
    (r'Ордер частично заполнен: ([\d.]+)%', r'Order partially filled: \1%'),
    (r'Ордер #(\d+) не найден в открытых ордерах', r'Order #\1 not found in open orders'),
    (r'Ордер найден в истории', 'Order found in history'),
    (r'✓ Ордер #(\d+) исполнен \(из истории\) @ ([\d.]+)', r'✓ Order #\1 executed (from history) @ \2'),
    (r'Ошибка проверки order history:', 'Error checking order history:'),
    (r'CloudFront блокирует открытые ордера \(это нормально при rate limiting\), продолжаем проверку позиций\.\.\.', 'CloudFront is blocking open orders (this is normal with rate limiting), continuing position check...'),
    (r'Ошибка проверки открытых ордеров:', 'Error checking open orders:'),
    (r'Логируем прогресс каждые 15 секунд', 'Logging progress every 15 seconds'),
    (r'⏳ Ожидание\.\.\. \(прошло: (\d+)с, осталось: (.+), лимитная цена: ([\d.]+)\)', r'⏳ Waiting... (elapsed: \1s, remaining: \2, limit price: \3)'),
    (r'Ордер #(\d+) не исполнен за (\d+)с \(([\d.]+)с\) - переставляем ближе к текущей цене\.\.\.', r'Order #\1 not executed for \2s (\3s) - repositioning closer to current price...'),
    (r'Новая лимитная цена: ([\d.]+) \(текущая: ([\d.]+), отступ: ([\d.]+)%\)', r'New limit price: \1 (current: \2, offset: \3%)'),
    (r'✓ Новый ордер #(\d+) размещён ближе к текущей цене', r'✓ New order #\1 placed closer to current price'),
    (r'Не удалось разместить новый ордер', 'Failed to place new order'),
    (r'Ожидание исполнения ордера #(\d+)\.\.\. \(лимитная цена: ([\d.]+), прошло: (\d+)с, осталось: (.+)\)', r'Waiting for order execution #\1... (limit price: \2, elapsed: \3s, remaining: \4)'),
    (r'CloudFront блокирует запросы \(попытка (\d+)\), продолжаем проверку\.\.\.', r'CloudFront is blocking requests (attempt \1), continuing check...'),
    (r'Ошибка проверки позиций:', 'Error checking positions:'),
    (r'⚠ Ордер #(\d+) не исполнился за (\d+) секунд \(([\d.]+) минут\)', r'⚠ Order #\1 was not executed for \2 seconds (\3 minutes)'),
    (r'Отменяем неисполненный ордер #(\d+)\.\.\.', r'Cancelling unexecuted order #\1...'),
    (r'Позиция НЕ открыта - ордер отменён из-за таймаута', 'Position NOT opened - order cancelled due to timeout'),
    (r'Мониторинг позиции: Entry @ ([\d.]+), Side: (.+)', r'Monitoring position: Entry @ \1, Side: \2'),
    (r'Take Profit: ([\d.]+)%, Stop Loss: ([\d.]+)%', r'Take Profit: \1%, Stop Loss: \2%'),
    (r'Примечание: Если TP/SL установлены на бирже, они сработают автоматически', 'Note: If TP/SL are set on exchange, they will trigger automatically'),
    (r'✓ Позиция закрыта автоматически \(вероятно, через TP/SL на бирже\)', '✓ Position closed automatically (probably via TP/SL on exchange)'),
    (r'Не удалось получить текущую цену для мониторинга', 'Failed to get current price for monitoring'),
    (r'Позиция активна \| Цена: ([\d.]+) \| PnL: ([\d.+-]+)% \| Осталось: (\d+)м ([\d.]+)с', r'Position active | Price: \1 | PnL: \2% | Remaining: \3m \4s'),
    (r'✓ Take profit достигнут программно! \+([\d.]+)% \(цель: ([\d.]+)%\)', r'✓ Take profit reached programmatically! +\1% (target: \2%)'),
    (r'Закрываем позицию вручную\.\.\.', 'Closing position manually...'),
    (r'✗ Stop loss достигнут программно! ([\d.+-]+)% \(лимит: ([\d.]+)%\)', r'✗ Stop loss reached programmatically! \1% (limit: \2%)'),
    (r'Время удержания истекло \(([\d.]+) минут\)', r'Hold time expired (\1 minutes)'),
    (r'Комиссии', 'Fees'),
    (r'Рандомизированные параметры для аккаунта:', 'Randomized parameters for account:'),
    (r'Плечо: (\d+)x', r'Leverage: \1x'),
    (r'Slippage: ([\d.]+)%', r'Slippage: \1%'),
    (r'Take Profit: ([\d.]+)%', r'Take Profit: \1%'),
    (r'Stop Loss: ([\d.]+)%', r'Stop Loss: \1%'),
    (r'Размер позиции: ([\d.]+)% - ([\d.]+)% от баланса \(без учета плеча\)', r'Position size: \1% - \2% of balance (without leverage)'),
    (r'Плечо (\d+)x превышает максимальное для некоторых рынков \((\d+)x\)\. Используем (\d+)x', r'Leverage \1x exceeds maximum for some markets (\2x). Using \3x'),
    (r'Попытка (\d+)/(\d+) получения баланса, ждём (\d+) сек\.\.\.', r'Attempt \1/\2 getting balance, waiting \3 sec...'),
    (r'✓ Баланс получен: \$([\d.]+)', r'✓ Balance received: $\1'),
    (r'❌ Не удалось получить баланс через API после всех попыток!', '❌ Failed to get balance via API after all attempts!'),
    (r'Проверьте:', 'Check:'),
    (r'Правильность API ключей в accounts\.csv', 'Correctness of API keys in accounts.csv'),
    (r'Бета доступ активирован на https://app\.pacifica\.fi', 'Beta access activated on https://app.pacifica.fi'),
    (r'Наличие средств на балансе', 'Presence of funds on balance'),
    (r'Останавливаем бота если нет баланса', 'Stopping bot if no balance'),
    (r'Объем: \$([\d.]+) / \$([\d.]+) \(([\d.]+)%\)', r'Volume: $\1 / $\2 (\3%)'),
    (r'PnL: \$([\d.]+) \| Сделок: (\d+)', r'PnL: $\1 | Trades: \2'),
    (r'Ожидание (\d+) секунд\.\.\.', r'Waiting \1 seconds...'),
    (r'Ошибка в цикле:', 'Error in cycle:'),
    (r'Целевой объем достигнут\. Закрытие всех позиций и отмена ордеров\.\.\.', 'Target volume reached. Closing all positions and cancelling orders...'),
    (r'Найдена открытая позиция ([A-Z]+), закрываем\.\.\.', r'Found open position \1, closing...'),
    (r'Бот завершил работу', 'Bot completed work'),
    (r'Итоговый объем: \$([\d.]+)', r'Final volume: $\1'),
    (r'Итоговый PnL: \$([\d.]+)', r'Final PnL: $\1'),
    (r'Настройка логирования', 'Setting up logging'),
    (r'Загрузка конфигурации', 'Loading configuration'),
    (r'Фильтруем только нужные поля \(поддерживаем новый формат с диапазонами\)', 'Filtering only needed fields (supporting new format with ranges)'),
    (r'Новый формат с диапазонами', 'New format with ranges'),
    (r'Старый формат \(для обратной совместимости\)', 'Old format (for backward compatibility)'),
    (r'Конвертируем старый формат в новый \(если нужно\)', 'Converting old format to new (if needed)'),
    (r'Файл accounts\.csv не найден!', 'File accounts.csv not found!'),
    (r'Нет аккаунтов в accounts\.csv', 'No accounts in accounts.csv'),
    (r'Определяем, используется ли API Agent или основной кошелек', 'Determining if API Agent or main wallet is used'),
    (r'Если api_key == walletaddress, значит это основной кошелек, а не API Agent', 'If api_key == walletaddress, then this is main wallet, not API Agent'),
    (r'Если api_key совпадает с main_account, значит это основной кошелек, не API Agent', 'If api_key matches main_account, then this is main wallet, not API Agent'),
    (r'Используем API Agent Keys: Agent=(.+), Main=(.+)', r'Using API Agent Keys: Agent=\1, Main=\2'),
    (r'Используем основной кошелёк (.+)', r'Using main wallet \1'),
    (r'Прервано пользователем', 'Interrupted by user'),
    (r'Критическая ошибка:', 'Critical error:'),
]

for pattern, replacement in logger_patterns:
    content = re.sub(pattern, replacement, content)

# Replace comments
comment_patterns = [
    (r'# Плечо \(фиксированное значение из конфига\)', '# Leverage (fixed value from config)'),
    (r'# Статистика', '# Statistics'),
    (r'# Конвертируем размер из USD в количество базовой валюты', '# Converting size from USD to base currency amount'),
    (r'# Размер в базовой валюте = размер в USD / цена', '# Size in base currency = size in USD / price'),
    (r'# Округляем до lot size', '# Rounding to lot size'),
    (r'# Limit ордер \(maker\) - округляем цену до tick size', '# Limit order (maker) - rounding price to tick size'),
    (r'# Market ордер', '# Market order'),
    (r'# Сначала закрываем все позиции', '# First closing all positions'),
    (r'# Ждём немного, чтобы позиции закрылись', '# Waiting a bit for positions to close'),
    (r'# Затем отменяем все оставшиеся ордера \(включая reduce-only\)', '# Then cancelling all remaining orders (including reduce-only)'),
    (r'# Ещё одна небольшая задержка для завершения операций', '# Another small delay for completing operations'),
    (r'# Ждём немного, чтобы ордер исполнился', '# Waiting a bit for order to execute'),
    (r'# Проверяем, закрылась ли позиция', '# Checking if position closed'),
    (r'# Если позиция закрыта, отменяем все открытые ордера для этого символа', '# If position closed, cancelling all open orders for this symbol'),
    (r'# Позиции нет, но проверим, нет ли открытых ордеров для этого символа', '# No position, but checking if there are open orders for this symbol'),
    (r'# Сначала проверяем, что позиция действительно открыта', '# First checking that position is really open'),
    (r'# Проверяем, что сторона позиции совпадает', '# Checking that position side matches'),
    (r'# Проверяем оба поля: funding_rate и next_funding_rate', '# Checking both fields: funding_rate and next_funding_rate'),
    (r'# Логируем для отладки', '# Logging for debugging'),
    (r'# Используем next_funding_rate \(следующий funding rate\)', '# Using next_funding_rate (next funding rate)'),
    (r'# так как он более актуален для принятия решений', '# as it is more relevant for decision making'),
    (r'# Округляем вниз до ближайшего кратного lot_size', '# Rounding down to nearest lot_size multiple'),
    (r'# Убираем лишние нули', '# Removing extra zeros'),
    (r'# Округляем до ближайшего кратного tick_size', '# Rounding to nearest tick_size multiple'),
    (r'# Определяем количество знаков после запятой из tick_size', '# Determining number of decimal places from tick_size'),
    (r'# Форматируем с правильным количеством знаков', '# Formatting with correct number of digits'),
    (r'# Проверяем, есть ли открытая позиция для этого символа', '# Checking if there is open position for this symbol'),
    (r'# Есть открытая позиция - получаем текущее плечо', '# There is open position - getting current leverage'),
    (r'# Если есть открытая позиция, проверяем правило: можно только увеличивать', '# If there is open position, checking rule: can only increase'),
    (r'# Проверяем максимальное плечо для рынка', '# Checking maximum leverage for market'),
    (r'# Проверяем, есть ли открытая позиция', '# Checking if there is open position'),
    (r'# Если ошибка о недопустимом плече', '# If error about invalid leverage'),
    (r'# Для открытых позиций можно только увеличивать плечо', '# For open positions, leverage can only be increased'),
    (r'# Пробуем увеличить плечо', '# Trying to increase leverage'),
    (r'# Пробуем увеличить плечо, начиная с leverage \+ 1 до max_leverage', '# Trying to increase leverage, starting from leverage + 1 to max_leverage'),
    (r'# Нет открытой позиции - пробуем уменьшить плечо', '# No open position - trying to decrease leverage'),
    (r'# Пробуем уменьшить плечо, начиная с leverage - 1 до 1', '# Trying to decrease leverage, starting from leverage - 1 to 1'),
    (r'# Если ошибка о недопустимом плече - пробуем уменьшить', '# If error about invalid leverage - trying to decrease'),
    (r'# Обновляем текущее плечо для этого рынка', '# Updating current leverage for this market'),
    (r'# В быстром режиме используем короткие задержки: 2, 4, 8 секунд', '# In fast mode using short delays: 2, 4, 8 seconds'),
    (r'# В обычном режиме: 3, 6, 12 секунд \(меньше, чем было\)', '# In normal mode: 3, 6, 12 seconds (less than before)'),
    (r'# Максимум 10 секунд', '# Maximum 10 seconds'),
    (r'# Максимум 15 секунд', '# Maximum 15 seconds'),
    (r'# Для других ошибок не делаем повторные попытки', '# For other errors not doing retries'),
    (r'# Согласно SDK: PriceInfo имеет поле \'mark\', а не \'mark_price\'', '# According to SDK: PriceInfo has field \'mark\', not \'mark_price\''),
    (r'# Проверяем разные поля для цены', '# Checking different fields for price'),
    (r'# Funding rate может быть в разных форматах:', '# Funding rate can be in different formats:'),
    (r'# - Как десятичная дробь: -0\.0003 = -0\.03%', '# - As decimal fraction: -0.0003 = -0.03%'),
    (r'# - Как процент: -0\.000003 = -0\.0003%', '# - As percentage: -0.000003 = -0.0003%'),
    (r'# Проверяем значение', '# Checking value'),
    (r'# Логируем в процентах для удобства', '# Logging in percentages for convenience'),
    (r'# SHORT - получаем funding', '# SHORT - receiving funding'),
    (r'# LONG - получаем funding', '# LONG - receiving funding'),
    (r'# Очистка перед новой сделкой: закрываем все позиции и отменяем все ордера', '# Cleanup before new trade: closing all positions and cancelling all orders'),
    (r'# Проверяем объем перед началом цикла', '# Checking volume before cycle start'),
    (r'# Выбор рынка', '# Selecting market'),
    (r'# Определение направления', '# Determining direction'),
    (r'# Используем кешированный баланс или получаем новый', '# Using cached balance or getting new one'),
    (r'# Расчет размера позиции', '# Calculating position size'),
    (r'# Получаем процент от баланса для позиции \(БЕЗ учета плеча\)', '# Getting percentage of balance for position (WITHOUT leverage)'),
    (r'# Рассчитываем размер позиции в USD \(БЕЗ плеча\)', '# Calculating position size in USD (WITHOUT leverage)'),
    (r'# position_percent - это процент от баланса, который мы используем', '# position_percent is percentage of balance that we use'),
    (r'# Комиссии \(maker ~0\.02%, taker ~0\.05%\)', '# Fees (maker ~0.02%, taker ~0.05%)'),
    (r'# 5% запас для безопасности', '# 5% safety buffer'),
    (r'# Учитываем комиссии и запас безопасности', '# Accounting for fees and safety buffer'),
    (r'# Комиссия берётся дважды \(открытие \+ закрытие\)', '# Fee is taken twice (opening + closing)'),
    (r'# Вычитаем комиссии из доступного баланса', '# Subtracting fees from available balance'),
    (r'# Ограничиваем размер позиции \(БЕЗ плеча\)', '# Limiting position size (WITHOUT leverage)'),
    (r'# Применяем плечо для расчета реального размера позиции на бирже', '# Applying leverage to calculate real position size on exchange'),
    (r'# position_size_base - это сколько USD мы используем из баланса', '# position_size_base is how much USD we use from balance'),
    (r'# position_size_usd - это размер позиции на бирже \(с плечом\)', '# position_size_usd is position size on exchange (with leverage)'),
    (r'# Проверяем, что у нас достаточно баланса', '# Checking that we have enough balance'),
    (r'# Уменьшаем процент позиции, если не хватает баланса', '# Decreasing position percentage if not enough balance'),
    (r'# Небольшая задержка, чтобы позиция точно появилась в системе', '# Small delay so position definitely appears in system'),
    (r'# Устанавливаем TP/SL через API', '# Setting TP/SL via API'),
    (r'# Сторона позиции \(bid для LONG, ask для SHORT\)', '# Position side (bid for LONG, ask for SHORT)'),
    (r'# Удержание позиции \(рандомизированное время\)', '# Holding position (randomized time)'),
    (r'# Закрытие позиции', '# Closing position'),
    (r'# Ждём закрытия и получаем цену закрытия', '# Waiting for closing and getting closing price'),
    (r'# Небольшая задержка для обновления позиций', '# Small delay for updating positions'),
    (r'# Для рыночных ордеров - они исполняются сразу', '# For market orders - they execute immediately'),
    (r'# Небольшая задержка для обработки', '# Small delay for processing'),
    (r'# Проверяем позиции для market ордера', '# Checking positions for market order'),
    (r'# Для лимитных ордеров - проверяем регулярно', '# For limit orders - checking regularly'),
    (r'# Проверяем каждые 5 секунд', '# Checking every 5 seconds'),
    (r'# Логируем прогресс каждые 15 секунд', '# Logging progress every 15 seconds'),
    (r'# Если не исполнился за отведённое время - отменяем ордер', '# If not executed within allotted time - cancelling order'),
    (r'# Согласно официальной документации Pacifica:', '# According to official Pacifica documentation:'),
    (r'# Проверяет:', '# Checks:'),
    (r'# 1\. Get open orders - открытые ордера', '# 1. Get open orders - open orders'),
    (r'# 2\. Get account positions - открытые позиции', '# 2. Get account positions - open positions'),
    (r'# 3\. Get order history by ID - история ордера', '# 3. Get order history by ID - order history'),
    (r'# Получаем order_id из ответа', '# Getting order_id from response'),
    (r'# Fallback: пробуем получить через markets \(если есть mark_price\)', '# Fallback: trying to get via markets (if mark_price exists)'),
    (r'# Сторона для стоп-ордеров \(противоположная позиции\)', '# Side for stop orders (opposite to position)'),
    (r'# Не показываем отрицательные значения', '# Not showing negative values'),
    (r'# Вычисляем максимальную ширину ASCII-арта и нормализуем все строки до этой ширины', '# Calculating maximum width of ASCII art and normalizing all lines to this width'),
    (r'# Отступы по 1 символу с каждой стороны', '# Padding of 1 character on each side'),
    (r'# \+2 для границ ║', '# +2 for borders ║'),
    (r'# Функция для создания строки с правильным выравниванием', '# Function for creating line with correct alignment'),
    (r'# Убираем лишние пробелы справа', '# Removing extra spaces on right'),
    (r'# Выводим ASCII-арт GOATHAM DAO', '# Displaying ASCII art GOATHAM DAO'),
    (r'# Настройка плеча \(используем рандомизированное значение\)', '# Setting leverage (using randomized value)'),
    (r'# Проверяем максимальные плечи для всех рынков и корректируем текущее плечо', '# Checking maximum leverages for all markets and adjusting current leverage'),
    (r'# Если текущее плечо превышает минимальное максимальное - ограничиваем', '# If current leverage exceeds minimum maximum - limiting'),
    (r'# Устанавливаем плечо для всех рынков', '# Setting leverage for all markets'),
    (r'# Задержка между запросами', '# Delay between requests'),
    (r'# Получение баланса \(с повторными попытками\)', '# Getting balance (with retries)'),
    (r'# CloudFront может блокировать запросы из-за rate limiting', '# CloudFront may block requests due to rate limiting'),
    (r'# Добавляем задержки и увеличиваем время между попытками', '# Adding delays and increasing time between attempts'),
    (r'# Задержка перед запросом \(избегаем rate limiting\)', '# Delay before request (avoiding rate limiting)'),
    (r'# Максимум 30 секунд', '# Maximum 30 seconds'),
    (r'# Основной цикл', '# Main cycle'),
    (r'# Проверяем возвращаемое значение trading_cycle', '# Checking returned value from trading_cycle'),
    (r'# Если объем достигнут, выходим из цикла', '# If volume reached, exiting cycle'),
    (r'# Статистика', '# Statistics'),
    (r'# Задержка \(рандомизированная\)', '# Delay (randomized)'),
    (r'# Целевой объем достигнут - закрываем все позиции и отменяем ордера', '# Target volume reached - closing all positions and cancelling orders'),
    (r'# Сначала отменяем все ордера', '# First cancelling all orders'),
    (r'# Затем закрываем все позиции', '# Then closing all positions'),
    (r'# Финальная проверка - убеждаемся, что все закрыто', '# Final check - making sure everything is closed'),
    (r'# Отменяем все оставшиеся ордера еще раз', '# Cancelling all remaining orders once more'),
    (r'# API Agent Keys:', '# API Agent Keys:'),
    (r'# private_key = приватный ключ API Agent \(api_secret\)', '# private_key = API Agent private key (api_secret)'),
    (r'# public_key = публичный ключ основного аккаунта \(walletaddress/subaccount\)', '# public_key = main account public key (walletaddress/subaccount)'),
    (r'# agent_wallet = публичный ключ API Agent \(api_key\)', '# agent_wallet = API Agent public key (api_key)'),
    (r'# Основной кошелёк:', '# Main wallet:'),
    (r'# private_key = приватный ключ основного кошелька', '# private_key = main wallet private key'),
    (r'# public_key = публичный ключ основного кошелька', '# public_key = main wallet public key'),
]

for pattern, replacement in comment_patterns:
    content = re.sub(pattern, replacement, content)

# Write the translated file
with open('pacifica_bot.py', 'w', encoding='utf-8') as f:
    f.write(content)

print("Translation complete! Check pacifica_bot.py")

