#!/usr/bin/env python3
"""Script to translate pacifica_bot.py from Russian to English"""

import re

# Read the file
with open('pacifica_bot.py', 'r', encoding='utf-8') as f:
    content = f.read()

# Translation dictionary for common phrases
translations = {
    # Docstrings and comments
    'Инициализация клиентов': 'Initializing clients',
    'Закрытие соединений': 'Closing connections',
    'Получение информации об аккаунте': 'Getting account information',
    'Получение доступного баланса': 'Getting available balance',
    'Получение списка рынков': 'Getting list of markets',
    'Получение текущих цен с таймаутом и повторными попытками': 'Getting current prices with timeout and retries',
    'Получение текущей цены для символа': 'Getting current price for symbol',
    'Получение funding rate для символа': 'Getting funding rate for symbol',
    'Получение tick size для символа': 'Getting tick size for symbol',
    'Получение lot size (минимальный размер ордера) для символа': 'Getting lot size (minimum order size) for symbol',
    'Округление количества до кратного lot size': 'Rounding amount to lot size multiple',
    'Округление цены до кратного tick size': 'Rounding price to tick size multiple',
    'Получение максимального плеча для рынка': 'Getting maximum leverage for market',
    'Установка плеча для рынка': 'Setting leverage for market',
    'Для открытых позиций можно только увеличивать плечо': 'For open positions, leverage can only be increased',
    'Получение открытых позиций с повторными попытками': 'Getting open positions with retries',
    'Размещение ордера': 'Placing order',
    'Отмена ордера': 'Canceling order',
    'Получение открытых ордеров': 'Getting open orders',
    'Отмена всех ордеров': 'Canceling all orders',
    'Закрытие всех открытых позиций': 'Closing all open positions',
    'Очистка перед новой сделкой': 'Cleaning up before new trade',
    'Закрытие позиции': 'Closing position',
    'Установка Take Profit и Stop Loss для позиции через API': 'Setting Take Profit and Stop Loss for position via API',
    'Выбор лучшего рынка на основе funding rate': 'Selecting best market based on funding rate',
    'Определение направления на основе funding rate': 'Determining direction based on funding rate',
    'Один цикл торговли': 'One trading cycle',
    'Ожидание исполнения ордера и получение реальной цены': 'Waiting for order execution and getting real price',
    'Удержание позиции с мониторингом': 'Holding position with monitoring',
    'Расчет PnL': 'Calculating PnL',
    'Запуск бота': 'Starting bot',
    'Главная функция': 'Main function',
    
    # Logger messages - will be replaced with regex
}

# Replace logger messages with Russian text
def translate_logger_msg(match):
    msg = match.group(1)
    # Common translations
    msg = msg.replace('Инициализация Pacifica клиентов...', 'Initializing Pacifica clients...')
    msg = msg.replace('✓ Info настроен с подписью для авторизованных GET запросов', '✓ Info configured with signature for authorized GET requests')
    msg = msg.replace('⚠ Exchange не имеет keypair - GET запросы к приватным эндпоинтам могут не работать', '⚠ Exchange does not have keypair - GET requests to private endpoints may not work')
    msg = msg.replace('✓ Клиенты инициализированы', '✓ Clients initialized')
    msg = msg.replace('Попытка через Info не удалась:', 'Attempt via Info failed:')
    msg = msg.replace('Ошибка HTTP', 'HTTP error')
    msg = msg.replace('Ошибка получения аккаунта:', 'Error getting account:')
    msg = msg.replace('Ошибка получения рынков:', 'Error getting markets:')
    msg = msg.replace('Запрос цен через API (попытка', 'Requesting prices via API (attempt')
    msg = msg.replace('из', 'of')
    msg = msg.replace(')...', ')...')
    msg = msg.replace('✓ Получено цен:', '✓ Received prices:')
    msg = msg.replace('Пустой ответ от API (попытка', 'Empty response from API (attempt')
    msg = msg.replace('Таймаут получения цен (попытка', 'Timeout getting prices (attempt')
    msg = msg.replace('Ошибка получения цен (попытка', 'Error getting prices (attempt')
    msg = msg.replace('CloudFront блокирует, ждём', 'CloudFront is blocking, waiting')
    msg = msg.replace('с...', 's...')
    msg = msg.replace('Не удалось получить цены после всех попыток', 'Failed to get prices after all attempts')
    msg = msg.replace('Цена', 'Price')
    msg = msg.replace('не найдена в prices, пробуем через markets...', 'not found in prices, trying via markets...')
    msg = msg.replace('из markets:', 'from markets:')
    msg = msg.replace('Ошибка получения цены через markets:', 'Error getting price via markets:')
    msg = msg.replace('Не удалось получить цену для', 'Failed to get price for')
    msg = msg.replace('Current funding:', 'Current funding:')
    msg = msg.replace('Next funding:', 'Next funding:')
    msg = msg.replace('Максимальное плечо для', 'Maximum leverage for')
    msg = msg.replace('Ошибка получения максимального плеча для', 'Error getting maximum leverage for')
    msg = msg.replace('Найдена открытая позиция', 'Found open position')
    msg = msg.replace('с плечом', 'with leverage')
    msg = msg.replace('⚠ Для открытой позиции', '⚠ For open position')
    msg = msg.replace('можно только УВЕЛИЧИВАТЬ плечо.', 'leverage can only be INCREASED.')
    msg = msg.replace('Текущее:', 'Current:')
    msg = msg.replace('запрошенное:', 'requested:')
    msg = msg.replace('Используем текущее', 'Using current')
    msg = msg.replace('Плечо', 'Leverage')
    msg = msg.replace('уже установлено на', 'already set to')
    msg = msg.replace('превышает максимальное для', 'exceeds maximum for')
    msg = msg.replace('Используем', 'Using')
    msg = msg.replace('слишком мало для', 'too low for')
    msg = msg.replace('Используем минимальное 1x', 'Using minimum 1x')
    msg = msg.replace('Не удалось получить максимальное плечо для', 'Failed to get maximum leverage for')
    msg = msg.replace('используем запрошенное', 'using requested')
    msg = msg.replace('✓ Плечо', '✓ Leverage')
    msg = msg.replace('установлено для', 'set for')
    msg = msg.replace('✗ Нельзя уменьшить плечо для открытой позиции', '✗ Cannot decrease leverage for open position')
    msg = msg.replace('недопустимо для', 'invalid for')
    msg = msg.replace('с открытой позицией.', 'with open position.')
    msg = msg.replace('Пробуем увеличить...', 'Trying to increase...')
    msg = msg.replace('Пробуем установить плечо', 'Trying to set leverage')
    msg = msg.replace('для', 'for')
    msg = msg.replace('...', '...')
    msg = msg.replace('(вместо запрошенного', '(instead of requested')
    msg = msg.replace('✗ Не удалось установить допустимое плечо для', '✗ Failed to set valid leverage for')
    msg = msg.replace('с открытой позицией', 'with open position')
    msg = msg.replace('(ошибка:', '(error:')
    msg = msg.replace('), пробуем уменьшить...', '), trying to decrease...')
    msg = msg.replace('Последняя ошибка:', 'Last error:')
    msg = msg.replace('Ошибка установки плеча для', 'Error setting leverage for')
    msg = msg.replace('пробуем уменьшить...', 'trying to decrease...')
    msg = msg.replace('Обновляем текущее плечо для этого рынка', 'Updating current leverage for this market')
    msg = msg.replace('✗ Не удалось установить допустимое плечо для', '✗ Failed to set valid leverage for')
    msg = msg.replace('Traceback:', 'Traceback:')
    msg = msg.replace('✓ Получено позиций:', '✓ Received positions:')
    msg = msg.replace('Позиция:', 'Position:')
    msg = msg.replace('amount=', 'amount=')
    msg = msg.replace('entry_price=', 'entry_price=')
    msg = msg.replace('N/A', 'N/A')
    msg = msg.replace('CloudFront блокирует (попытка', 'CloudFront is blocking (attempt')
    msg = msg.replace('), ждём', '), waiting')
    msg = msg.replace('с...', 's...')
    msg = msg.replace('CloudFront блокирует после', 'CloudFront is blocking after')
    msg = msg.replace('попыток, возвращаем пустой список', 'attempts, returning empty list')
    msg = msg.replace('Ошибка получения позиций:', 'Error getting positions:')
    msg = msg.replace('Размер округлён до lot size', 'Size rounded to lot size')
    msg = msg.replace('Размер ордера слишком мал:', 'Order size too small:')
    msg = msg.replace('✓ Ордер размещен:', '✓ Order placed:')
    msg = msg.replace('Ошибка размещения ордера:', 'Error placing order:')
    msg = msg.replace('✓ Ордер #', '✓ Order #')
    msg = msg.replace('отменён', 'cancelled')
    msg = msg.replace('Ошибка отмены ордера #', 'Error canceling order #')
    msg = msg.replace('Ошибка получения открытых ордеров:', 'Error getting open orders:')
    msg = msg.replace('Отмена всех ордеров для', 'Canceling all orders for')
    msg = msg.replace('...', '...')
    msg = msg.replace('Отмена всех ордеров для всех символов...', 'Canceling all orders for all symbols...')
    msg = msg.replace('✓ Отменено ордеров:', '✓ Cancelled orders:')
    msg = msg.replace('Не удалось получить информацию об отменённых ордерах', 'Failed to get information about cancelled orders')
    msg = msg.replace('Ошибка отмены всех ордеров:', 'Error canceling all orders:')
    msg = msg.replace('Нет открытых позиций для закрытия', 'No open positions to close')
    msg = msg.replace('Закрытие позиции', 'Closing position')
    msg = msg.replace('✓ Закрыто позиций:', '✓ Closed positions:')
    msg = msg.replace('Ошибка закрытия всех позиций:', 'Error closing all positions:')
    msg = msg.replace('🧹 Очистка перед новой сделкой...', '🧹 Cleaning up before new trade...')
    msg = msg.replace('✓ Очистка завершена', '✓ Cleanup completed')
    msg = msg.replace('Не удалось получить цену для закрытия позиции', 'Failed to get price for closing position')
    msg = msg.replace('позиция', 'position')
    msg = msg.replace('закрываем через', 'closing via')
    msg = msg.replace('размер:', 'size:')
    msg = msg.replace('закрыта, проверяем открытые ордера...', 'closed, checking open orders...')
    msg = msg.replace('Найдено', 'Found')
    msg = msg.replace('открытых ордеров для', 'open orders for')
    msg = msg.replace('отменяем...', 'cancelling...')
    msg = msg.replace('Нет открытых ордеров для', 'No open orders for')
    msg = msg.replace('нет, но найдено', 'not found, but found')
    msg = msg.replace('Сторона позиции не совпадает: ожидали', 'Position side does not match: expected')
    msg = msg.replace('получили', 'got')
    msg = msg.replace('не найдена, не можем установить TP/SL', 'not found, cannot set TP/SL')
    msg = msg.replace('Не удалось получить tick_size для', 'Failed to get tick_size for')
    msg = msg.replace('используем округление до 2 знаков', 'using rounding to 2 decimal places')
    msg = msg.replace('Расчёт TP/SL для', 'Calculating TP/SL for')
    msg = msg.replace('Entry=', 'Entry=')
    msg = msg.replace('TP=', 'TP=')
    msg = msg.replace('SL=', 'SL=')
    msg = msg.replace('Отправка запроса TP/SL: symbol=', 'Sending TP/SL request: symbol=')
    msg = msg.replace('стоп-ордера=', 'stop orders=')
    msg = msg.replace('✓ TP/SL установлены для', '✓ TP/SL set for')
    msg = msg.replace('⚠ Не удалось установить TP/SL для', '⚠ Failed to set TP/SL for')
    msg = msg.replace('Пустой ответ от API при установке TP/SL для', 'Empty response from API when setting TP/SL for')
    msg = msg.replace('API ошибка при установке TP/SL для', 'API error when setting TP/SL for')
    msg = msg.replace('Server ошибка при установке TP/SL для', 'Server error when setting TP/SL for')
    msg = msg.replace('Ошибка установки TP/SL для', 'Error setting TP/SL for')
    msg = msg.replace('Ошибка анализа', 'Error analyzing')
    msg = msg.replace('Не удалось получить funding rate для', 'Failed to get funding rate for')
    msg = msg.replace('для', 'for')
    msg = msg.replace(':', ':')
    msg = msg.replace('Funding rate положительный, открываем SHORT (получаем funding)', 'Funding rate positive, opening SHORT (receiving funding)')
    msg = msg.replace('Funding rate отрицательный, открываем LONG (получаем funding)', 'Funding rate negative, opening LONG (receiving funding)')
    msg = msg.replace('True если целевой объем достигнут, False иначе', 'True if target volume reached, False otherwise')
    msg = msg.replace('Нет доступных рынков', 'No available markets')
    msg = msg.replace('Выбран рынок:', 'Selected market:')
    msg = msg.replace('Не удалось определить направление для', 'Failed to determine direction for')
    msg = msg.replace('Недостаточно средств или баланс не получен', 'Insufficient funds or balance not received')
    msg = msg.replace('Не удалось получить цену для', 'Failed to get price for')
    msg = msg.replace('Размер позиции:', 'Position size:')
    msg = msg.replace('от баланса', 'of balance')
    msg = msg.replace('без плеча', 'without leverage')
    msg = msg.replace('с плечом', 'with leverage')
    msg = msg.replace('уменьшен до', 'decreased to')
    msg = msg.replace('Лимитная цена:', 'Limit price:')
    msg = msg.replace('текущая:', 'current:')
    msg = msg.replace('отступ:', 'offset:')
    msg = msg.replace('Не удалось открыть позицию', 'Failed to open position')
    msg = msg.replace('Ожидание исполнения ордера...', 'Waiting for order execution...')
    msg = msg.replace('❌ Ордер не был исполнен - позиция НЕ открыта', '❌ Order was not executed - position NOT opened')
    msg = msg.replace('Бот пропустит эту сделку и перейдёт к следующей', 'Bot will skip this trade and move to next')
    msg = msg.replace('✓ Позиция открыта @', '✓ Position opened @')
    msg = msg.replace('Установка Take Profit и Stop Loss через API...', 'Setting Take Profit and Stop Loss via API...')
    msg = msg.replace('⚠ Не удалось установить TP/SL через API, бот будет мониторить вручную', '⚠ Failed to set TP/SL via API, bot will monitor manually')
    msg = msg.replace('Удержание позиции', 'Holding position')
    msg = msg.replace('минут', 'minutes')
    msg = msg.replace('секунд)...', 'seconds)...')
    msg = msg.replace('Закрытие позиции', 'Closing position')
    msg = msg.replace('Не удалось получить цену закрытия', 'Failed to get closing price')
    msg = msg.replace('Не удалось закрыть позицию', 'Failed to close position')
    msg = msg.replace('✓ Сделка #', '✓ Trade #')
    msg = msg.replace('закрыта | Exit:', 'closed | Exit:')
    msg = msg.replace('Объём сделки:', 'Trade volume:')
    msg = msg.replace('Общий объём:', 'Total volume:')
    msg = msg.replace('Общий PnL:', 'Total PnL:')
    msg = msg.replace('=== Ожидание исполнения ордера #', '=== Waiting for order execution #')
    msg = msg.replace('===', '===')
    msg = msg.replace('Сторона:', 'Side:')
    msg = msg.replace('Market ордер - проверяем исполнение...', 'Market order - checking execution...')
    msg = msg.replace('✓ Market ордер исполнен @', '✓ Market order executed @')
    msg = msg.replace('✓ Market ордер исполнен! Позиция:', '✓ Market order executed! Position:')
    msg = msg.replace('Максимум ожидания:', 'Maximum wait:')
    msg = msg.replace('перестановка через:', 'repositioning via:')
    msg = msg.replace('Интервал проверки:', 'Check interval:')
    msg = msg.replace('[', '[')
    msg = msg.replace('с] Проверка позиций для', 's] Checking positions for')
    msg = msg.replace('...', '...')
    msg = msg.replace('✓ Найдена позиция по', '✓ Found position for')
    msg = msg.replace('✓✓✓ ОРДЕР #', '✓✓✓ ORDER #')
    msg = msg.replace('ИСПОЛНЕН! ✓✓✓', 'EXECUTED! ✓✓✓')
    msg = msg.replace('⚠ Позиция найдена, но amount слишком мал:', '⚠ Position found, but amount too small:')
    msg = msg.replace('Открытых ордеров:', 'Open orders:')
    msg = msg.replace('Ордер #', 'Order #')
    msg = msg.replace('найден в открытых ордерах', 'found in open orders')
    msg = msg.replace('Заполнение:', 'Filling:')
    msg = msg.replace('Осталось:', 'Remaining:')
    msg = msg.replace('почти исполнен! @', 'almost executed! @')
    msg = msg.replace('✓ Позиция подтверждена:', '✓ Position confirmed:')
    msg = msg.replace('Ордер частично заполнен:', 'Order partially filled:')
    msg = msg.replace('не найден в открытых ордерах', 'not found in open orders')
    msg = msg.replace('Ордер найден в истории', 'Order found in history')
    msg = msg.replace('исполнен (из истории) @', 'executed (from history) @')
    msg = msg.replace('Ошибка проверки order history:', 'Error checking order history:')
    msg = msg.replace('CloudFront блокирует открытые ордера (это нормально при rate limiting), продолжаем проверку позиций...', 'CloudFront is blocking open orders (this is normal with rate limiting), continuing position check...')
    msg = msg.replace('Ошибка проверки открытых ордеров:', 'Error checking open orders:')
    msg = msg.replace('Логируем прогресс каждые 15 секунд', 'Logging progress every 15 seconds')
    msg = msg.replace('⏳ Ожидание... (прошло:', '⏳ Waiting... (elapsed:')
    msg = msg.replace('с, осталось:', 's, remaining:')
    msg = msg.replace('лимитная цена:', 'limit price:')
    msg = msg.replace('не исполнен за', 'not executed for')
    msg = msg.replace(') - переставляем ближе к текущей цене...', ') - repositioning closer to current price...')
    msg = msg.replace('Новая лимитная цена:', 'New limit price:')
    msg = msg.replace('✓ Новый ордер #', '✓ New order #')
    msg = msg.replace('размещён ближе к текущей цене', 'placed closer to current price')
    msg = msg.replace('Не удалось разместить новый ордер', 'Failed to place new order')
    msg = msg.replace('Ожидание исполнения ордера #', 'Waiting for order execution #')
    msg = msg.replace('прошло:', 'elapsed:')
    msg = msg.replace('CloudFront блокирует запросы (попытка', 'CloudFront is blocking requests (attempt')
    msg = msg.replace('), продолжаем проверку...', '), continuing check...')
    msg = msg.replace('Ошибка проверки позиций:', 'Error checking positions:')
    msg = msg.replace('⚠ Ордер #', '⚠ Order #')
    msg = msg.replace('не исполнился за', 'was not executed for')
    msg = msg.replace('секунд (', 'seconds (')
    msg = msg.replace('минут)', 'minutes)')
    msg = msg.replace('Отменяем неисполненный ордер #', 'Cancelling unexecuted order #')
    msg = msg.replace('...', '...')
    msg = msg.replace('Позиция НЕ открыта - ордер отменён из-за таймаута', 'Position NOT opened - order cancelled due to timeout')
    msg = msg.replace('Мониторинг позиции: Entry @', 'Monitoring position: Entry @')
    msg = msg.replace('Примечание: Если TP/SL установлены на бирже, они сработают автоматически', 'Note: If TP/SL are set on exchange, they will trigger automatically')
    msg = msg.replace('✓ Позиция закрыта автоматически (вероятно, через TP/SL на бирже)', '✓ Position closed automatically (probably via TP/SL on exchange)')
    msg = msg.replace('Не удалось получить текущую цену для мониторинга', 'Failed to get current price for monitoring')
    msg = msg.replace('Позиция активна |', 'Position active |')
    msg = msg.replace('Осталось:', 'Remaining:')
    msg = msg.replace('м', 'm')
    msg = msg.replace('с', 's')
    msg = msg.replace('✓ Take profit достигнут программно! +', '✓ Take profit reached programmatically! +')
    msg = msg.replace('% (цель:', '% (target:')
    msg = msg.replace('%)', '%)')
    msg = msg.replace('Закрываем позицию вручную...', 'Closing position manually...')
    msg = msg.replace('✗ Stop loss достигнут программно!', '✗ Stop loss reached programmatically!')
    msg = msg.replace('% (лимит:', '% (limit:')
    msg = msg.replace('Время удержания истекло (', 'Hold time expired (')
    msg = msg.replace('минут)', 'minutes)')
    msg = msg.replace('Комиссии', 'Fees')
    msg = msg.replace('Рандомизированные параметры для аккаунта:', 'Randomized parameters for account:')
    msg = msg.replace('Плечо:', 'Leverage:')
    msg = msg.replace('Slippage:', 'Slippage:')
    msg = msg.replace('Take Profit:', 'Take Profit:')
    msg = msg.replace('Stop Loss:', 'Stop Loss:')
    msg = msg.replace('Размер позиции:', 'Position size:')
    msg = msg.replace('от баланса (без учета плеча)', 'of balance (without leverage)')
    msg = msg.replace('превышает максимальное для некоторых рынков (', 'exceeds maximum for some markets (')
    msg = msg.replace('). Используем', '). Using')
    msg = msg.replace('Попытка', 'Attempt')
    msg = msg.replace('получения баланса, ждём', 'getting balance, waiting')
    msg = msg.replace('сек...', 'sec...')
    msg = msg.replace('✓ Баланс получен:', '✓ Balance received:')
    msg = msg.replace('❌ Не удалось получить баланс через API после всех попыток!', '❌ Failed to get balance via API after all attempts!')
    msg = msg.replace('Проверьте:', 'Check:')
    msg = msg.replace('Правильность API ключей в accounts.csv', 'Correctness of API keys in accounts.csv')
    msg = msg.replace('Бета доступ активирован на https://app.pacifica.fi', 'Beta access activated on https://app.pacifica.fi')
    msg = msg.replace('Наличие средств на балансе', 'Presence of funds on balance')
    msg = msg.replace('Останавливаем бота если нет баланса', 'Stopping bot if no balance')
    msg = msg.replace('Объем:', 'Volume:')
    msg = msg.replace('Сделок:', 'Trades:')
    msg = msg.replace('Ожидание', 'Waiting')
    msg = msg.replace('секунд...', 'seconds...')
    msg = msg.replace('Ошибка в цикле:', 'Error in cycle:')
    msg = msg.replace('Целевой объем достигнут. Закрытие всех позиций и отмена ордеров...', 'Target volume reached. Closing all positions and cancelling orders...')
    msg = msg.replace('Найдена открытая позиция', 'Found open position')
    msg = msg.replace('закрываем...', 'closing...')
    msg = msg.replace('Бот завершил работу', 'Bot completed work')
    msg = msg.replace('Итоговый объем:', 'Final volume:')
    msg = msg.replace('Итоговый PnL:', 'Final PnL:')
    msg = msg.replace('Настройка логирования', 'Setting up logging')
    msg = msg.replace('Загрузка конфигурации', 'Loading configuration')
    msg = msg.replace('Фильтруем только нужные поля (поддерживаем новый формат с диапазонами)', 'Filtering only needed fields (supporting new format with ranges)')
    msg = msg.replace('Новый формат с диапазонами', 'New format with ranges')
    msg = msg.replace('Старый формат (для обратной совместимости)', 'Old format (for backward compatibility)')
    msg = msg.replace('Конвертируем старый формат в новый (если нужно)', 'Converting old format to new (if needed)')
    msg = msg.replace('Файл accounts.csv не найден!', 'File accounts.csv not found!')
    msg = msg.replace('Нет аккаунтов в accounts.csv', 'No accounts in accounts.csv')
    msg = msg.replace('Определяем, используется ли API Agent или основной кошелек', 'Determining if API Agent or main wallet is used')
    msg = msg.replace('Если api_key == walletaddress, значит это основной кошелек, а не API Agent', 'If api_key == walletaddress, then this is main wallet, not API Agent')
    msg = msg.replace('Если api_key совпадает с main_account, значит это основной кошелек, не API Agent', 'If api_key matches main_account, then this is main wallet, not API Agent')
    msg = msg.replace('Используем API Agent Keys: Agent=', 'Using API Agent Keys: Agent=')
    msg = msg.replace('Main=', 'Main=')
    msg = msg.replace('Используем основной кошелёк', 'Using main wallet')
    msg = msg.replace('Прервано пользователем', 'Interrupted by user')
    msg = msg.replace('Критическая ошибка:', 'Critical error:')
    
    # Comments
    msg = msg.replace('# Плечо (фиксированное значение из конфига)', '# Leverage (fixed value from config)')
    msg = msg.replace('# Статистика', '# Statistics')
    msg = msg.replace('# Конвертируем размер из USD в количество базовой валюты', '# Converting size from USD to base currency amount')
    msg = msg.replace('# Размер в базовой валюте = размер в USD / цена', '# Size in base currency = size in USD / price')
    msg = msg.replace('# Округляем до lot size', '# Rounding to lot size')
    msg = msg.replace('# Limit ордер (maker) - округляем цену до tick size', '# Limit order (maker) - rounding price to tick size')
    msg = msg.replace('# Market ордер', '# Market order')
    msg = msg.replace('# Сначала закрываем все позиции', '# First closing all positions')
    msg = msg.replace('# Ждём немного, чтобы позиции закрылись', '# Waiting a bit for positions to close')
    msg = msg.replace('# Затем отменяем все оставшиеся ордера (включая reduce-only)', '# Then cancelling all remaining orders (including reduce-only)')
    msg = msg.replace('# Ещё одна небольшая задержка для завершения операций', '# Another small delay for completing operations')
    msg = msg.replace('# Ждём немного, чтобы ордер исполнился', '# Waiting a bit for order to execute')
    msg = msg.replace('# Проверяем, закрылась ли позиция', '# Checking if position closed')
    msg = msg.replace('# Если позиция закрыта, отменяем все открытые ордера для этого символа', '# If position closed, cancelling all open orders for this symbol')
    msg = msg.replace('# Позиции нет, но проверим, нет ли открытых ордеров для этого символа', '# No position, but checking if there are open orders for this symbol')
    msg = msg.replace('# Сначала проверяем, что позиция действительно открыта', '# First checking that position is really open')
    msg = msg.replace('# Проверяем, что сторона позиции совпадает', '# Checking that position side matches')
    msg = msg.replace('# Проверяем оба поля: funding_rate и next_funding_rate', '# Checking both fields: funding_rate and next_funding_rate')
    msg = msg.replace('# Логируем для отладки', '# Logging for debugging')
    msg = msg.replace('# Используем next_funding_rate (следующий funding rate)', '# Using next_funding_rate (next funding rate)')
    msg = msg.replace('# так как он более актуален для принятия решений', '# as it is more relevant for decision making')
    msg = msg.replace('# Округляем вниз до ближайшего кратного lot_size', '# Rounding down to nearest lot_size multiple')
    msg = msg.replace('# Убираем лишние нули', '# Removing extra zeros')
    msg = msg.replace('# Округляем до ближайшего кратного tick_size', '# Rounding to nearest tick_size multiple')
    msg = msg.replace('# Определяем количество знаков после запятой из tick_size', '# Determining number of decimal places from tick_size')
    msg = msg.replace('# Форматируем с правильным количеством знаков', '# Formatting with correct number of digits')
    msg = msg.replace('# Проверяем, есть ли открытая позиция для этого символа', '# Checking if there is open position for this symbol')
    msg = msg.replace('# Есть открытая позиция - получаем текущее плечо', '# There is open position - getting current leverage')
    msg = msg.replace('# Если есть открытая позиция, проверяем правило: можно только увеличивать', '# If there is open position, checking rule: can only increase')
    msg = msg.replace('# Проверяем максимальное плечо для рынка', '# Checking maximum leverage for market')
    msg = msg.replace('# Проверяем, есть ли открытая позиция', '# Checking if there is open position')
    msg = msg.replace('# Если ошибка о недопустимом плече', '# If error about invalid leverage')
    msg = msg.replace('# Для открытых позиций можно только увеличивать плечо', '# For open positions, leverage can only be increased')
    msg = msg.replace('# Пробуем увеличить плечо', '# Trying to increase leverage')
    msg = msg.replace('# Пробуем увеличить плечо, начиная с leverage + 1 до max_leverage', '# Trying to increase leverage, starting from leverage + 1 to max_leverage')
    msg = msg.replace('# Нет открытой позиции - пробуем уменьшить плечо', '# No open position - trying to decrease leverage')
    msg = msg.replace('# Пробуем уменьшить плечо, начиная с leverage - 1 до 1', '# Trying to decrease leverage, starting from leverage - 1 to 1')
    msg = msg.replace('# Если ошибка о недопустимом плече - пробуем уменьшить', '# If error about invalid leverage - trying to decrease')
    msg = msg.replace('# Обновляем текущее плечо для этого рынка', '# Updating current leverage for this market')
    msg = msg.replace('# В быстром режиме используем короткие задержки: 2, 4, 8 секунд', '# In fast mode using short delays: 2, 4, 8 seconds')
    msg = msg.replace('# В обычном режиме: 3, 6, 12 секунд (меньше, чем было)', '# In normal mode: 3, 6, 12 seconds (less than before)')
    msg = msg.replace('# Максимум 10 секунд', '# Maximum 10 seconds')
    msg = msg.replace('# Максимум 15 секунд', '# Maximum 15 seconds')
    msg = msg.replace('# Для других ошибок не делаем повторные попытки', '# For other errors not doing retries')
    msg = msg.replace('# Согласно SDK: PriceInfo имеет поле \'mark\', а не \'mark_price\'', '# According to SDK: PriceInfo has field \'mark\', not \'mark_price\'')
    msg = msg.replace('# Проверяем разные поля для цены', '# Checking different fields for price')
    msg = msg.replace('# Funding rate может быть в разных форматах:', '# Funding rate can be in different formats:')
    msg = msg.replace('# - Как десятичная дробь: -0.0003 = -0.03%', '# - As decimal fraction: -0.0003 = -0.03%')
    msg = msg.replace('# - Как процент: -0.000003 = -0.0003%', '# - As percentage: -0.000003 = -0.0003%')
    msg = msg.replace('# Проверяем значение', '# Checking value')
    msg = msg.replace('# Логируем в процентах для удобства', '# Logging in percentages for convenience')
    msg = msg.replace('# SHORT - получаем funding', '# SHORT - receiving funding')
    msg = msg.replace('# LONG - получаем funding', '# LONG - receiving funding')
    msg = msg.replace('# Очистка перед новой сделкой: закрываем все позиции и отменяем все ордера', '# Cleanup before new trade: closing all positions and cancelling all orders')
    msg = msg.replace('# Проверяем объем перед началом цикла', '# Checking volume before cycle start')
    msg = msg.replace('# Выбор рынка', '# Selecting market')
    msg = msg.replace('# Определение направления', '# Determining direction')
    msg = msg.replace('# Используем кешированный баланс или получаем новый', '# Using cached balance or getting new one')
    msg = msg.replace('# Расчет размера позиции', '# Calculating position size')
    msg = msg.replace('# Получаем процент от баланса для позиции (БЕЗ учета плеча)', '# Getting percentage of balance for position (WITHOUT leverage)')
    msg = msg.replace('# Рассчитываем размер позиции в USD (БЕЗ плеча)', '# Calculating position size in USD (WITHOUT leverage)')
    msg = msg.replace('# position_percent - это процент от баланса, который мы используем', '# position_percent is percentage of balance that we use')
    msg = msg.replace('# Комиссии (maker ~0.02%, taker ~0.05%)', '# Fees (maker ~0.02%, taker ~0.05%)')
    msg = msg.replace('# 5% запас для безопасности', '# 5% safety buffer')
    msg = msg.replace('# Учитываем комиссии и запас безопасности', '# Accounting for fees and safety buffer')
    msg = msg.replace('# Комиссия берётся дважды (открытие + закрытие)', '# Fee is taken twice (opening + closing)')
    msg = msg.replace('# Вычитаем комиссии из доступного баланса', '# Subtracting fees from available balance')
    msg = msg.replace('# Ограничиваем размер позиции (БЕЗ плеча)', '# Limiting position size (WITHOUT leverage)')
    msg = msg.replace('# Применяем плечо для расчета реального размера позиции на бирже', '# Applying leverage to calculate real position size on exchange')
    msg = msg.replace('# position_size_base - это сколько USD мы используем из баланса', '# position_size_base is how much USD we use from balance')
    msg = msg.replace('# position_size_usd - это размер позиции на бирже (с плечом)', '# position_size_usd is position size on exchange (with leverage)')
    msg = msg.replace('# Проверяем, что у нас достаточно баланса', '# Checking that we have enough balance')
    msg = msg.replace('# Уменьшаем процент позиции, если не хватает баланса', '# Decreasing position percentage if not enough balance')
    msg = msg.replace('# Небольшая задержка, чтобы позиция точно появилась в системе', '# Small delay so position definitely appears in system')
    msg = msg.replace('# Устанавливаем TP/SL через API', '# Setting TP/SL via API')
    msg = msg.replace('# Сторона позиции (bid для LONG, ask для SHORT)', '# Position side (bid for LONG, ask for SHORT)')
    msg = msg.replace('# Удержание позиции (рандомизированное время)', '# Holding position (randomized time)')
    msg = msg.replace('# Закрытие позиции', '# Closing position')
    msg = msg.replace('# Ждём закрытия и получаем цену закрытия', '# Waiting for closing and getting closing price')
    msg = msg.replace('# Небольшая задержка для обновления позиций', '# Small delay for updating positions')
    msg = msg.replace('# Для рыночных ордеров - они исполняются сразу', '# For market orders - they execute immediately')
    msg = msg.replace('# Небольшая задержка для обработки', '# Small delay for processing')
    msg = msg.replace('# Проверяем позиции для market ордера', '# Checking positions for market order')
    msg = msg.replace('# Для лимитных ордеров - проверяем регулярно', '# For limit orders - checking regularly')
    msg = msg.replace('# Проверяем каждые 5 секунд', '# Checking every 5 seconds')
    msg = msg.replace('# Логируем прогресс каждые 15 секунд', '# Logging progress every 15 seconds')
    msg = msg.replace('# Если не исполнился за отведённое время - отменяем ордер', '# If not executed within allotted time - cancelling order')
    msg = msg.replace('# Согласно официальной документации Pacifica:', '# According to official Pacifica documentation:')
    msg = msg.replace('# Проверяет:', '# Checks:')
    msg = msg.replace('# 1. Get open orders - открытые ордера', '# 1. Get open orders - open orders')
    msg = msg.replace('# 2. Get account positions - открытые позиции', '# 2. Get account positions - open positions')
    msg = msg.replace('# 3. Get order history by ID - история ордера', '# 3. Get order history by ID - order history')
    msg = msg.replace('# Получаем order_id из ответа', '# Getting order_id from response')
    msg = msg.replace('# Получаем order_id из ответа', '# Getting order_id from response')
    msg = msg.replace('# Согласно SDK: PriceInfo имеет поле \'mark\', а не \'mark_price\'', '# According to SDK: PriceInfo has field \'mark\', not \'mark_price\'')
    msg = msg.replace('# Fallback: пробуем получить через markets (если есть mark_price)', '# Fallback: trying to get via markets (if mark_price exists)')
    msg = msg.replace('# Согласно SDK: PriceInfo имеет поле \'mark\', а не \'mark_price\'', '# According to SDK: PriceInfo has field \'mark\', not \'mark_price\'')
    msg = msg.replace('# Сторона для стоп-ордеров (противоположная позиции)', '# Side for stop orders (opposite to position)')
    msg = msg.replace('# Не показываем отрицательные значения', '# Not showing negative values')
    msg = msg.replace('# Вычисляем максимальную ширину ASCII-арта и нормализуем все строки до этой ширины', '# Calculating maximum width of ASCII art and normalizing all lines to this width')
    msg = msg.replace('# Отступы по 1 символу с каждой стороны', '# Padding of 1 character on each side')
    msg = msg.replace('# +2 для границ ║', '# +2 for borders ║')
    msg = msg.replace('# Функция для создания строки с правильным выравниванием', '# Function for creating line with correct alignment')
    msg = msg.replace('# Убираем лишние пробелы справа', '# Removing extra spaces on right')
    msg = msg.replace('# Выводим ASCII-арт GOATHAM DAO', '# Displaying ASCII art GOATHAM DAO')
    msg = msg.replace('# Настройка плеча (используем рандомизированное значение)', '# Setting leverage (using randomized value)')
    msg = msg.replace('# Проверяем максимальные плечи для всех рынков и корректируем текущее плечо', '# Checking maximum leverages for all markets and adjusting current leverage')
    msg = msg.replace('# Если текущее плечо превышает минимальное максимальное - ограничиваем', '# If current leverage exceeds minimum maximum - limiting')
    msg = msg.replace('# Устанавливаем плечо для всех рынков', '# Setting leverage for all markets')
    msg = msg.replace('# Задержка между запросами', '# Delay between requests')
    msg = msg.replace('# Получение баланса (с повторными попытками)', '# Getting balance (with retries)')
    msg = msg.replace('# CloudFront может блокировать запросы из-за rate limiting', '# CloudFront may block requests due to rate limiting')
    msg = msg.replace('# Добавляем задержки и увеличиваем время между попытками', '# Adding delays and increasing time between attempts')
    msg = msg.replace('# Задержка перед запросом (избегаем rate limiting)', '# Delay before request (avoiding rate limiting)')
    msg = msg.replace('# Максимум 30 секунд', '# Maximum 30 seconds')
    msg = msg.replace('# Основной цикл', '# Main cycle')
    msg = msg.replace('# Проверяем возвращаемое значение trading_cycle', '# Checking returned value from trading_cycle')
    msg = msg.replace('# Если объем достигнут, выходим из цикла', '# If volume reached, exiting cycle')
    msg = msg.replace('# Статистика', '# Statistics')
    msg = msg.replace('# Задержка (рандомизированная)', '# Delay (randomized)')
    msg = msg.replace('# Целевой объем достигнут - закрываем все позиции и отменяем ордера', '# Target volume reached - closing all positions and cancelling orders')
    msg = msg.replace('# Сначала отменяем все ордера', '# First cancelling all orders')
    msg = msg.replace('# Затем закрываем все позиции', '# Then closing all positions')
    msg = msg.replace('# Финальная проверка - убеждаемся, что все закрыто', '# Final check - making sure everything is closed')
    msg = msg.replace('# Отменяем все оставшиеся ордера еще раз', '# Cancelling all remaining orders once more')
    msg = msg.replace('# API Agent Keys:', '# API Agent Keys:')
    msg = msg.replace('# private_key = приватный ключ API Agent (api_secret)', '# private_key = API Agent private key (api_secret)')
    msg = msg.replace('# public_key = публичный ключ основного аккаунта (walletaddress/subaccount)', '# public_key = main account public key (walletaddress/subaccount)')
    msg = msg.replace('# agent_wallet = публичный ключ API Agent (api_key)', '# agent_wallet = API Agent public key (api_key)')
    msg = msg.replace('# Основной кошелёк:', '# Main wallet:')
    msg = msg.replace('# private_key = приватный ключ основного кошелька', '# private_key = main wallet private key')
    msg = msg.replace('# public_key = публичный ключ основного кошелька', '# public_key = main wallet public key')
    
    return msg

# Replace all logger calls
content = re.sub(r'logger\.(info|error|warning|debug)\(f?"([^"]*)"', 
                 lambda m: f'logger.{m.group(1)}(f"{translate_logger_msg(m)}"', content)

# Replace docstrings
content = re.sub(r'"""[^"]*"""', translate_logger_msg, content)

# Write translated file
with open('pacifica_bot.py', 'w', encoding='utf-8') as f:
    f.write(content)

print("Translation complete!")

